### ISSUE TITLE
Running on macOS

### ISSUE THREAD

**Issue by sbis04** [michaellee8/flutter_fuchsia_toolchain#2]
I am trying to use this tool on macOS, but I found it's only configured for Linux systems. Is there any modification you can suggest which may help me in using this tool on macOS?

**Comment by michaellee8** [comment]
This toolchain depends on the [GN C++ frontend SDK](https://fuchsia.dev/fuchsia-src/development/idk/gn) which only supports Linux host. However, it seems that building Fuchsia from source will allow you to use it on macOS, as guided in https://fuchsia.dev/fuchsia-src/get-started/build_fuchsia. You may build fuchsia from source on macOS and then developing apps with it in Flutter.

Alternatively, if your mac device is powerful enough, you can consider enabling neated virtualization and then use this toolchain inside a Linux VM, but the performance cost is very large for this method through.

**Comment by sbis04** [comment]
Actually, I have access to both **Linux** and **macOS** systems. I have already followed the official docs and got the Fuchsia emulator running on my **macOS**, but I am not able to figure out how to get a Flutter app running on it. And, it seems that the docs for building a Flutter module is also outdated and incomplete. It would be great if you can help me in running that.

There is one `examples` folder inside the fuchsia repo, I tried running some CLI apps present there and was successfully able to build, compile and run. Like I tried the hello_world in both c++ and dart both of them ran. I tried the same process for running a Flutter app (there is one present inside the examples folder called `webview_mod`). But it couldn't find the module, for GUI based apps I guess the process is a bit different.

**Comment by michaellee8** [comment]
Let's continue discussion in #3 , there are specify steps to pave a flutter app into a fuchsia instance and it should have been handled by this toolchain and the guide, let me do some catch up first.
